name: puupee_api_client
version: 1.0.0+5
description: Api for puupee app service.
homepage: https://github.com/puupee/puupee-api-dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
